server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alcohol?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 32
      maximum-pool-size: 64
      idle-timeout: 600000
      max-lifetime: 540000
      connection-timeout: 60000
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true
      encoding: UTF-8
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    database: 0
    jedis:
      pool:
        max-active: 32
        max-wait: -1
        min-idle: 32
        max-idle: 64
    connect-timeout: 30000

knife4j:
  enabled: true
  basic:
    enabled: true
    username: gin
    password: gin

config:
  encryptor:
    password: misaka mikoto!!!

auth:
  basic:
    enabled: true
    username: gin
    password: gin

kir:
  hero:
    url: https://game.gtimg.cn

#mybatis 枚举处理
mybatis:
  configuration:
    default-enum-type-handler: com.gin.handler.BaseEnumTypeHandler

#tk.mybatis 通用Mapper枚举处理
mapper:
  enum-as-simple-type: true