name: Publish to GitHub Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure maven setting
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>${{ github.actor }}</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PERSONAL_ACCESS_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and publish
        run: mvn -B clean deploy -pl !bourbon,!gin,!scotch -am -Dmaven.test.skip=true