name: Deploy to GitHub Package

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure maven setting
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>${{ github.actor }}</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PERSONAL_ACCESS_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Delete old version
        run: |
          sudo apt-get install -y libxml2-utils
          bash delete.sh

      - name: Build and publish
        run: mvn -B clean deploy -pl ${{ env.excluded_projects }} -am -Dmaven.test.skip=true