name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          settings-path: ${{ github.workspace }}

      - name: Generate settings.xml
        run: |
          cat <<EOF > ${{ github.workspace }}/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>${{ github.actor }}</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PERSONAL_ACCESS_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF  

      - name: Build and Publish
        run: bash deploy_maven.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}